spring:
  profiles:
    active: dev
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait:
        max-idle: 8
        min-idle: 0
  main:
    allow-bean-definition-overriding: true

