spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
#    没有起作用 并没有抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
girl:
  cupSize: B
  age: 18
boy :
   name : zhangsan
   age: 19

man : "${boy}"
women : a


logging:
  level:
    root: debug
    org.apache.http.wire: debug
    org.apache.http.headers: debug
  config: classpath:logback-spring.xml
